# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               McCollem
tagline:             'Code|Run'
description:         'A blog about coding, running, and everything in between.'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             0.0.3

github: 			 
  repo: 			 https://github.com/mccollem/mccollem.github.io
