# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true 

# Setup
title:               McCollem
tagline:             'Code|Run'
description:         'A blog about coding, running, and everything in between.'
url:                 
baseurl:             /
#paginate:            5
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             0.0.3

github: 			 
  repo: 			 https://github.com/mccollem/mccollem.github.io
