# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               McCollem
tagline:             'Code|Run'
description:         'A blog about coding, running, and everything in between.'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             0.0.2

github: 			 https://github.com/mccollem/
  repo: 			 mccollem.github.io
