# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            McCollem
tagline:          'Run|Code|Sleep'
description:      'Run|Code|Sleep'
url:              
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           
